mod draw_call_ordering;
mod instance;
pub mod lazy_instance;
pub mod renderer;
mod svg_geometry;
pub mod tessellator;
mod vertex;
pub mod vertex_buffers;
pub use instance::VectorInstance;
pub use renderer::VectorRenderer;
